# language: node_js
# rvm:
#   - 12.13.0
#   -  

# branches:
#   only:
#   - master
# cache:
#   directories:
#     - node_modules
# before_install:
#   - mysql -e 'CREATE DATABASE testdb;'
#   - npm i -g npm@version-number
  
